config/routes.rb
Rails.application.routes.draw do
  root 'songs#list'
  get 'songs/list' => 'songs#list', as: :song_list
  get 'songs/new' => 'songs#new', as: :new_song
  post 'songs/create' => 'songs#create', as: :songs
  delete 'songs/destroy/:id' => 'songs#destroy', as: :delete_song
  get 'songs/edit/:id' => 'songs#edit', as: :edit_song
  post 'songs/update/:id' => 'songs#update', as: :song
  
  resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :duration, presence: true
  validates :duration, numericality: true

  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  def list 
    @songs = Song.all
  end
  
  def new 
    @song = Song.new 
    artist_collection
  end
  
  def create
    @song = Song.create(song_params)
    if @song.persisted?
      redirect_to song_list_path
    else 
      artist_collection
      render 'new'
    end
  end
  
  def destroy
    song = Song.find(params["id"])
    song.destroy
    redirect_to song_list_path
  end
  
  def edit 
    @song = Song.find(params["id"])
    artist_collection
    render 'new'
  end
  
  def update
    @song = Song.find(params['id'])
    if @song.update(song_params)
      redirect_to song_list_path
    else
      artist_collection
      render 'new'
    end
  end
  
  private 
  
  def artist_collection
    @artists = Artist.all.map { |artist| [artist.name, artist.id] }  
  end
  
  def song_params
    params.require(:song).permit(:name, :duration, :artist_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = ['joe', 'john', 'jimmy', 'caitlyn', 'natalie'].sort
  end
  
  def foo
    @users = ['other', 'names', 'that', 'are', 'more', 'diverse']
    render 'index'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.name %></td>
    </tr>
  <% end %>
</table>

app/views/artists/new.html.erb
<%= form_for @artist, method: 'post' do |f|  %>

  <%= render "shared/form_errors", model: @artist %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit "Create it man" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SongList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <h1>Best Songlist Eva!</h1>
    <ul>
      <li><%= link_to "List Artists", artists_path %></li>
      <li><%= link_to "New Song",   new_song_path %></li>
      <li><%= link_to "List songs", song_list_path %></li>
    </ul>
    <div>
      <%= yield %>
    </div>  
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this song from being saved:</h2>

    <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/songs/list.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @songs.each do |song| %>
    <tr>
      <td><%= song.name %></td>
      <td><%= song.duration %></td>
      <td><%= link_to "X", edit_song_path(song.id) %></td>
      <td><%= link_to "X", delete_song_path(song.id), method: 'delete' %></td>  
    </tr>
  <% end %>
</table>

app/views/songs/new.html.erb
<%= form_for @song, method: 'post' do |f|  %>

  <%= render "shared/form_errors", model: @song %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :duration %>
  <%= f.number_field :duration %>
  <%= f.label :artist_id %>
  <%= f.select :artist_id, @artists %>
  <%= f.submit "Submit me bro" %>
<% end %>

app/views/users/index.html.erb
<h1>User List</h1>

<ul>
  <% @users.each do |user|  %>
    <li><%= user %></li>
  <% end %>
</ul>